env                                           = "dev"
region                                        = "us-east-1"
aws_account_number                            = "332281781429"
created_by                                    = "BizCloudExperts"
application                                   = "omni-project44-real-time-updates"
omni_ltl_location_update_api_url              = "https://na12.api.project44.com/api/v4/capacityproviders/ltl/shipments/statusupdates"
